sudo: false
language: haskell
ghc: 8.2
cache:
  directories:
  - dist-newstyle

install: []
script:
- cabal new-build haskell-tree-sitter:test && dist-newstyle/build/semantic-diff-0.3.0/build/test/test
