flags: {}
extra-package-dbs: []
packages:
- '.'
- location: languages/go
  extra-dep: true
- location: languages/python
  extra-dep: true
- location: languages/typescript
  extra-dep: true
- location: languages/json
  extra-dep: true
- location: languages/ruby
  extra-dep: true
extra-deps:
- c-storable-deriving-0.1.3
resolver: nightly-2017-09-10
