flags: {}
extra-package-dbs: []
packages:
- '.'
- location: languages/go
- location: languages/php
- location: languages/python
- location: languages/typescript
- location: languages/json
- location: languages/ruby
- location: languages/haskell
  extra-dep: true
resolver: lts-13.13
extra-deps:
  - fused-effects-0.4.0.0
ghc-options:
    "$targets": -ddump-splices
    "$everything": -O0
